
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5431
  username: root
  password: root
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: cashback_service_development

test:
  <<: *default
  database: cashback_service_test

production:
  url: postgres://eyaedtgmrcybbv:b87f8f37345c1f553944ba44c7eeb51afecd40ebbe017767469279a869a91ba2@ec2-34-233-186-251.compute-1.amazonaws.com:5432/d57ocl7s9cudoh

