
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5431
  username: root
  password: root
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: cashback_service_development

test:
  <<: *default
  database: cashback_service_test

production:
  <<: *default
  database: cashback_service_production
  host: ec2-54-210-128-153.compute-1.amazonaws.com
  port: 5432
  username: cscaukuywpsxrl
  password: de1dcae2a3644a8a719c8e89af28db97410a642f031ce271e922e729d6e71345
